### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by fabn** [seatgeek/soulmate#47]
I read that [Seatgeek no longer uses Soulmate](https://news.ycombinator.com/item?id=9317891) and I see that a [fork of this project](https://github.com/sethherr/soulheart) is born.

I find this project very useful when one needs only autocompletion and not full text search, however I'd like to know if it's worth to rely on this project anymore.

What's the current project status? Will it be updated?

Please advice

**Comment by josegonzalez** [comment]
The project still works - code doesn't have an expiration date! - and we'd be happy to merge any pull requests. I just got back from vacation, but I'll take a look at the open PRs this weekend :)

**Comment by fabn** [comment]
Ok, thanks for the update.

**Comment by sethherr** [comment]
Hey @josegonzalez, I did [fork the project](https://github.com/sethherr/soulheart) to add some features that I wanted to have, and I'm pretty excited about the updates. Can I add a link to Soulmate's readme?

**Comment by josegonzalez** [comment]
How does your project differ? Ideally we just combine the two and call it a day :)

**Comment by sethherr** [comment]
Well... I thought about that, and it's what I originally intended. But I realized it would be better off not being backward compatible.

There are minor things, like using cors instead of jsonp, but also major things, like the way that you load data in and the server response. The parameters passed to the server have all been renamed. When you submit multiple categories (soulmate calls them "types"), my updated fork responds with weighted projects of any of the categories, rather than separate lists.

**Comment by josegonzalez** [comment]
Backwards compatibility can be broken by major releases ;)

**Comment by sethherr** [comment]
After thinking about it for a while, I'm going to continue on with soulheart as a separate gem.

It feels like a new project (with different goals) and I feel guilty about my reckless commit history. I hope you aren't too sad.

**Comment by josegonzalez** [comment]
No worries, that's how open source works :)
